version: '3'
services:
  web:
    image: "node:16"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
    command: "yarn start"
